site_name: My Tech Log
site_url: https://robo-education.github.io/robo-education.git/
site_description: GitHub Page + MkDocs 설정 Note
site_author: deoneo@naver.com

repo_name: robos-education/robos-education.github.io
repo_url: https://github.com/robos-education/robos-education.github.io

theme:
  name: material
  language: ko

  palette:              # mode toggle 사용
    - scheme: default
      primary: custom # indigo # css의 사용자 정의를 사용한다.
      accent: custom # indigo
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - scheme: slate
      primary: custom # indigo
      accent: custom # indigo
      toggle:
        icon: material/brightness-4
        name: Light Mode

  font:
    text: Noto Sans KR
    code: Noto Sans Mono    # 한국어 지원 고정폭 폰트

  icon:
    logo: material/book-open-page-variant   # 파일로 만들어 설정할 수 있다.(assets/logo.png)
  favicon: assets/favicon.png             # local에서 안보일 수 있다.

  features:
    - navigation.top           # 스크롤 내리면 맨 위로 버튼 표시
    - navigation.footer        # 페이지 하단에 이전/다음 페이지 버튼
    # - navigation.tabs          # 상단에 탭 메뉴 표시
    - search.highlight         # 검색 결과 강조
    - search.suggest           # 검색 자동완성
    - content.code.copy        # 코드 블록에 복사 버튼 추가

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:       # code highlight 사용
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true   # checkbox 디자인을 Material theme 사용
  - tables
  - toc:
      permalink: true         # 제목에 아이콘 붙혀준다.
  - footnotes

copyright: Copyright &copy; 2026 삼산 Robos
extra:
  generator: false        # 하단에 MkDocs theme 표시하지 않음"

# 3. 플러그인 설정 (★redirect★)
plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': '01_intro.md'