name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: ["main"] # main 브랜치에 푸시될 때 자동으로 실행됩니다.

# 깃허브 페이지 배포를 위해 필요한 최소한의 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시에 여러 번 푸시될 경우, 이전 배포를 취소하고 최신 배포만 진행하도록 설정
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      # 1. 깃허브 가상 서버로 소스코드를 체크아웃(가져오기) 합니다.
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 가상 서버에 파이썬 환경을 설치합니다. (MkDocs 실행을 위한 필수 베이스)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. MkDocs 및 Material 테마 플러그인을 설치합니다.
      - name: Install dependencies
        run: pip install mkdocs-material mkdocs-redirects mkdocs-toggle-sidebar-plugin mkdocs-awesome-nav

      # 4. 마크다운(.md) 문서들을 HTML 웹사이트로 빌드합니다. (site 폴더 생성)
      - name: Build with MkDocs
        run: mkdocs build

      # 5. 깃허브 페이지 시스템 환경을 초기화합니다.
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6. 빌드 결과물인 './site' 폴더를 압축하여 배포 자산(Artifact)으로 업로드합니다.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      # 7. 업로드된 자산을 바탕으로 실제 깃허브 웹사이트로 최종 배포합니다.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
